server:
    port: 8080
spring:
    application:
        name: api
    datasource:
        url: jdbc:postgresql://localhost:5432/promart
        username: chaitanya
        password: chaitanya
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    security:
        jwt:
            secret: 28ce7324417bd2c4dd6f506941db222b5701e2927b8cfceac9d908a757f11254
            expiration: 86400000